
-- PostgreSQL schema for Retrosheet master CSVs
-- Based on Retrosheet "Contents of CSV Download Files" documentation.

CREATE SCHEMA IF NOT EXISTS retrosheet;

-- allplayers.csv
CREATE TABLE IF NOT EXISTS retrosheet.allplayers (
    id          TEXT PRIMARY KEY, -- RetroID
    last        TEXT NOT NULL,
    first       TEXT NOT NULL,
    bat         CHAR(1) NOT NULL, -- B/L/R/?
    "throw"     CHAR(1) NOT NULL,
    team        TEXT NOT NULL, -- Retrosheet TeamID
    g           INTEGER,
    g_p         INTEGER,
    g_sp        INTEGER,
    g_rp        INTEGER,
    g_c         INTEGER,
    g_1b        INTEGER,
    g_2b        INTEGER,
    g_3b        INTEGER,
    g_ss        INTEGER,
    g_lf        INTEGER,
    g_cf        INTEGER,
    g_rf        INTEGER,
    g_of        INTEGER,
    g_dh        INTEGER,
    g_ph        INTEGER,
    g_pr        INTEGER,
    first_g     DATE,
    last_g      DATE,
    season      INTEGER,
    CONSTRAINT allplayers_unique_team_season UNIQUE (id, team, season)
);

CREATE INDEX IF NOT EXISTS idx_allplayers_team_season ON retrosheet.allplayers(team, season);

-- gameinfo.csv
CREATE TABLE IF NOT EXISTS retrosheet.gameinfo (
    gid         TEXT PRIMARY KEY,
    visteam     TEXT NOT NULL,
    hometeam    TEXT NOT NULL,
    site        TEXT,
    date        DATE NOT NULL,
    number      INTEGER NOT NULL,
    starttime   TEXT,
    daynight    TEXT,
    innings     INTEGER,
    tiebreaker  TEXT,
    usedh       TEXT,
    htbf        TEXT,
    timeofgame  INTEGER,
    attendance  INTEGER,
    fieldcond   TEXT,
    precip      TEXT,
    sky         TEXT,
    temp        INTEGER,
    winddir     TEXT,
    windspeed   INTEGER,
    oscorer     TEXT,
    forfeit     TEXT,
    suspend     TEXT,
    umphome     TEXT,
    ump1b       TEXT,
    ump2b       TEXT,
    ump3b       TEXT,
    umplf       TEXT,
    umprf       TEXT,
    wp          TEXT,
    lp          TEXT,
    save        TEXT,
    gametype    TEXT,
    vruns       INTEGER,
    hruns       INTEGER,
    wteam       TEXT,
    lteam       TEXT,
    line        TEXT,
    batteries   TEXT,
    lineups     TEXT,
    box         TEXT,
    pbp         TEXT,
    season      INTEGER
);

CREATE INDEX IF NOT EXISTS idx_gameinfo_season ON retrosheet.gameinfo(season);
CREATE INDEX IF NOT NOT EXISTS idx_gameinfo_teams ON retrosheet.gameinfo(visteam, hometeam);

-- teamstats.csv
CREATE TABLE IF NOT EXISTS retrosheet.teamstats (
    gid         TEXT NOT NULL,
    team        TEXT NOT NULL,
    inn1        INTEGER,
    inn2        INTEGER,
    inn3        INTEGER,
    inn4        INTEGER,
    inn5        INTEGER,
    inn6        INTEGER,
    inn7        INTEGER,
    inn8        INTEGER,
    inn9        INTEGER,
    inn10       INTEGER,
    inn11       INTEGER,
    inn12       INTEGER,
    inn13       INTEGER,
    inn14       INTEGER,
    inn15       INTEGER,
    inn16       INTEGER,
    inn17       INTEGER,
    inn18       INTEGER,
    inn19       INTEGER,
    inn20       INTEGER,
    inn21       INTEGER,
    inn22       INTEGER,
    inn23       INTEGER,
    inn24       INTEGER,
    inn25       INTEGER,
    inn26       INTEGER,
    inn27       INTEGER,
    inn28       INTEGER,
    lob         INTEGER,
    mgr         TEXT,
    stattype    TEXT NOT NULL,
    b_pa        INTEGER,
    b_ab        INTEGER,
    b_r         INTEGER,
    b_h         INTEGER,
    b_d         INTEGER,
    b_t         INTEGER,
    b_hr        INTEGER,
    b_rbi       INTEGER,
    b_sh        INTEGER,
    b_sf        INTEGER,
    b_hbp       INTEGER,
    b_w         INTEGER,
    b_iw        INTEGER,
    b_k         INTEGER,
    b_sb        INTEGER,
    b_cs        INTEGER,
    b_gdp       INTEGER,
    b_xi        INTEGER,
    b_roe       INTEGER,
    p_ipouts    INTEGER,
    p_noout     INTEGER,
    p_bfp       INTEGER,
    p_h         INTEGER,
    p_d         INTEGER,
    p_t         INTEGER,
    p_hr        INTEGER,
    p_r         INTEGER,
    p_er        INTEGER,
    p_w         INTEGER,
    p_iw        INTEGER,
    p_k         INTEGER,
    p_hbp       INTEGER,
    p_wp        INTEGER,
    p_bk        INTEGER,
    p_sh        INTEGER,
    p_sf        INTEGER,
    p_sb        INTEGER,
    p_cs        INTEGER,
    p_pb        INTEGER,
    d_po        INTEGER,
    d_a         INTEGER,
    d_e         INTEGER,
    d_dp        INTEGER,
    d_tp        INTEGER,
    d_pb        INTEGER,
    d_wp        INTEGER,
    d_sb        INTEGER,
    d_cs        INTEGER,
    start_l1    TEXT,
    start_l2    TEXT,
    start_l3    TEXT,
    start_l4    TEXT,
    start_l5    TEXT,
    start_l6    TEXT,
    start_l7    TEXT,
    start_l8    TEXT,
    start_l9    TEXT,
    start_f1    TEXT,
    start_f2    TEXT,
    start_f3    TEXT,
    start_f4    TEXT,
    start_f5    TEXT,
    start_f6    TEXT,
    start_f7    TEXT,
    start_f8    TEXT,
    start_f9    TEXT,
    start_f10   TEXT,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, team, stattype)
);

CREATE INDEX IF NOT EXISTS idx_teamstats_team ON retrosheet.teamstats(team);

-- batting.csv
CREATE TABLE IF NOT EXISTS retrosheet.batting (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    b_lp        INTEGER,
    b_seq       INTEGER,
    stattype    TEXT NOT NULL,
    b_pa        INTEGER,
    b_ab        INTEGER,
    b_r         INTEGER,
    b_h         INTEGER,
    b_d         INTEGER,
    b_t         INTEGER,
    b_hr        INTEGER,
    b_rbi       INTEGER,
    b_sh        INTEGER,
    b_sf        INTEGER,
    b_hbp       INTEGER,
    b_w         INTEGER,
    b_iw        INTEGER,
    b_k         INTEGER,
    b_sb        INTEGER,
    b_cs        INTEGER,
    b_gdp       INTEGER,
    b_xi        INTEGER,
    b_roe       INTEGER,
    dh          INTEGER,
    ph          INTEGER,
    pr          INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, stattype)
);

CREATE INDEX IF NOT EXISTS idx_batting_player ON retrosheet.batting(id);

-- pitching.csv
CREATE TABLE IF NOT EXISTS retrosheet.pitching (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    p_seq       INTEGER,
    stattype    TEXT NOT NULL,
    p_ipouts    INTEGER,
    p_noout     INTEGER,
    p_bfp       INTEGER,
    p_h         INTEGER,
    p_d         INTEGER,
    p_t         INTEGER,
    p_hr        INTEGER,
    p_r         INTEGER,
    p_er        INTEGER,
    p_w         INTEGER,
    p_iw        INTEGER,
    p_k         INTEGER,
    p_hbp       INTEGER,
    p_wp        INTEGER,
    p_bk        INTEGER,
    p_sh        INTEGER,
    p_sf        INTEGER,
    p_sb        INTEGER,
    p_cs        INTEGER,
    p_pb        INTEGER,
    wp          INTEGER,
    lp          INTEGER,
    save        INTEGER,
    gs          INTEGER,
    gf          INTEGER,
    cg          INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, stattype)
);

CREATE INDEX IF NOT EXISTS idx_pitching_player ON retrosheet.pitching(id);

-- fielding.csv
CREATE TABLE IF NOT EXISTS retrosheet.fielding (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    d_seq       INTEGER,
    d_pos       INTEGER,
    stattype    TEXT NOT NULL,
    d_ifouts    INTEGER,
    d_po        INTEGER,
    d_a         INTEGER,
    d_e         INTEGER,
    d_dp        INTEGER,
    d_tp        INTEGER,
    d_pb        INTEGER,
    d_wp        INTEGER,
    d_sb        INTEGER,
    d_cs        INTEGER,
    d_gs        INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, d_seq, d_pos, stattype)
);

CREATE INDEX IF NOT EXISTS idx_fielding_player ON retrosheet.fielding(id);

-- plays.csv (very wide; keep raw to start)
CREATE TABLE IF NOT EXISTS retrosheet.plays_raw (
    gid         TEXT NOT NULL,
    event       TEXT NOT NULL,
    inning      INTEGER,
    top_bot     INTEGER,
    vis_home    INTEGER,
    site        TEXT,
    batteam     TEXT,
    pitteam     TEXT,
    score_v     INTEGER,
    score_h     INTEGER,
    batter      TEXT,
    pitcher     TEXT,
    lp          INTEGER,
    bat_f       INTEGER,
    bathand     CHAR(1),
    pithand     CHAR(1),
    balls       INTEGER,
    strikes     INTEGER,
    "count"     TEXT,
    pitches     TEXT,
    nump        INTEGER,
    pa          INTEGER,
    ab          INTEGER,
    single      INTEGER,
    double      INTEGER,
    triple      INTEGER,
    hr          INTEGER,
    sh          INTEGER,
    sf          INTEGER,
    hbp         INTEGER,
    walk        INTEGER,
    k           INTEGER,
    xi          INTEGER,
    roe         INTEGER,
    fc          INTEGER,
    othout      INTEGER,
    noout       INTEGER,
    oth         INTEGER,
    bip         INTEGER,
    bunt        INTEGER,
    ground      INTEGER,
    fly         INTEGER,
    line        INTEGER,
    iw          INTEGER,
    gdp         INTEGER,
    othdp       INTEGER,
    tp          INTEGER,
    fle         INTEGER,
    wp          INTEGER,
    pb          INTEGER,
    bk          INTEGER,
    oa          INTEGER,
    di          INTEGER,
    sb2         INTEGER,
    sb3         INTEGER,
    sbh         INTEGER,
    cs2         INTEGER,
    cs3         INTEGER,
    csh         INTEGER,
    pko1        INTEGER,
    pko2        INTEGER,
    pko3        INTEGER,
    k_safe      INTEGER,
    e1          INTEGER,
    e2          INTEGER,
    e3          INTEGER,
    e4          INTEGER,
    e5          INTEGER,
    e6          INTEGER,
    e7          INTEGER,
    e8          INTEGER,
    e9          INTEGER,
    outs_pre    INTEGER,
    outs_post   INTEGER,
    br1_pre     TEXT,
    br2_pre     TEXT,
    br3_pre     TEXT,
    br1_post    TEXT,
    br2_post    TEXT,
    br3_post    TEXT,
    lob_id1     TEXT,
    lob_id2     TEXT,
    lob_id3     TEXT,
    pr1_pre     TEXT,
    pr2_pre     TEXT,
    pr3_pre     TEXT,
    pr1_post    TEXT,
    pr2_post    TEXT,
    pr3_post    TEXT,
    run_b       TEXT,
    run1        TEXT,
    run2        TEXT,
    run3        TEXT,
    prun_b      TEXT,
    prun1       TEXT,
    prun2       TEXT,
    prun3       TEXT,
    ur_b        INTEGER,
    ur1         INTEGER,
    ur2         INTEGER,
    ur3         INTEGER,
    rbi_b       INTEGER,
    rbi1        INTEGER,
    rbi2        INTEGER,
    rbi3        INTEGER,
    runs        INTEGER,
    rbi         INTEGER,
    er          INTEGER,
    tur         INTEGER,
    l1          TEXT,
    l2          TEXT,
    l3          TEXT,
    l4          TEXT,
    l5          TEXT,
    l6          TEXT,
    l7          TEXT,
    l8          TEXT,
    l9          TEXT,
    lf1         INTEGER,
    lf2         INTEGER,
    lf3         INTEGER,
    lf4         INTEGER,
    lf5         INTEGER,
    lf6         INTEGER,
    lf7         INTEGER,
    lf8         INTEGER,
    lf9         INTEGER,
    f2          TEXT,
    f3          TEXT,
    f4          TEXT,
    f5          TEXT,
    f6          TEXT,
    f7          TEXT,
    f8          TEXT,
    f9          TEXT,
    po0         INTEGER,
    po1         INTEGER,
    po2         INTEGER,
    po3         INTEGER,
    po4         INTEGER,
    po5         INTEGER,
    po6         INTEGER,
    po7         INTEGER,
    po8         INTEGER,
    po9         INTEGER,
    a1          INTEGER,
    a2          INTEGER,
    a3          INTEGER,
    a4          INTEGER,
    a5          INTEGER,
    a6          INTEGER,
    a7          INTEGER,
    a8          INTEGER,
    a9          INTEGER,
    fseq        TEXT,
    batout1     INTEGER,
    batout2     INTEGER,
    batout3     INTEGER,
    brout_b     INTEGER,
    brout1      INTEGER,
    brout2      INTEGER,
    brout3      INTEGER,
    firstf      INTEGER,
    loc         TEXT,
    hittype     TEXT,
    dpopp       INTEGER,
    pivot       INTEGER,
    pn          INTEGER,
    umphome     TEXT,
    ump1b       TEXT,
    ump2b       TEXT,
    ump3b       TEXT,
    umplf       TEXT,
    umprf       TEXT,
    date        DATE,
    gametype    TEXT,
    pbp         TEXT
);

CREATE INDEX IF NOT EXISTS idx_plays_gid_pn ON retrosheet.plays_raw(gid, pn);
