-- PostgreSQL schema for Retrosheet data
-- Includes exhaustive metadata and column descriptions (comments).

CREATE SCHEMA IF NOT EXISTS retrosheet;

-- ==========================================
-- 1. Personnel & Biographical Data
-- ==========================================

CREATE TABLE IF NOT EXISTS retrosheet.personnel (
    id              TEXT PRIMARY KEY,
    lastname        TEXT,
    usename         TEXT,
    fullname        TEXT,
    birthdate       DATE,
    birthcity       TEXT,
    birthstate      TEXT,
    birthcountry    TEXT,
    deathdate       DATE,
    deathcity       TEXT,
    deathstate      TEXT,
    deathcountry    TEXT,
    cemetery        TEXT,
    cem_city        TEXT,
    cem_state       TEXT,
    cem_ctry        TEXT,
    cem_note        TEXT,
    birthname       TEXT,
    altname         TEXT,
    debut_p         DATE,
    last_p          DATE,
    debut_c         DATE,
    last_c          DATE,
    debut_m         DATE,
    last_m          DATE,
    debut_u         DATE,
    last_u          DATE,
    bats            CHAR(1),
    throws          CHAR(1),
    height          INTEGER,
    weight          INTEGER,
    hof             TEXT
);

COMMENT ON TABLE retrosheet.personnel IS 'Master biographical information for all players, managers, coaches, and umpires.';
COMMENT ON COLUMN retrosheet.personnel.id IS 'Unique Retrosheet Person ID (usually 8 chars).';
COMMENT ON COLUMN retrosheet.personnel.usename IS 'The first name the person was commonly known by.';
COMMENT ON COLUMN retrosheet.personnel.debut_p IS 'Date of the first game played.';
COMMENT ON COLUMN retrosheet.personnel.hof IS 'Hall of Fame status (marked HOF if inducted).';

-- ==========================================
-- 2. Infrastructure (Parks & Teams)
-- ==========================================

CREATE TABLE IF NOT EXISTS retrosheet.parks (
    site            TEXT PRIMARY KEY,
    name            TEXT,
    city            TEXT,
    state           TEXT,
    first_g         DATE,
    last_g          DATE
);

COMMENT ON TABLE retrosheet.parks IS 'Directory of all ballparks where Retrosheet-tracked games were played.';
COMMENT ON COLUMN retrosheet.parks.site IS 'Unique Retrosheet Ballpark ID (e.g., NYC16).';

CREATE TABLE IF NOT EXISTS retrosheet.teams (
    team            TEXT PRIMARY KEY,
    city            TEXT,
    nickname        TEXT,
    first_g         DATE,
    last_g          DATE
);

COMMENT ON TABLE retrosheet.teams IS 'Master list of team franchises and their active date ranges.';

-- ==========================================
-- 3. Game Records (Logs & Metadata)
-- ==========================================

-- 161 fields as defined by Retrosheet
CREATE TABLE IF NOT EXISTS retrosheet.gamelogs (
    game_date               DATE,
    game_number             INTEGER,
    day_of_week             VARCHAR(3),
    visiting_team           VARCHAR(3),
    visiting_league         VARCHAR(2),
    visiting_game_number    INTEGER,
    home_team               VARCHAR(3),
    home_league             VARCHAR(2),
    home_game_number        INTEGER,
    visiting_score          INTEGER,
    home_score              INTEGER,
    outs_total              INTEGER,
    day_night               CHAR(1),
    completion_info         TEXT,
    forfeit_info            CHAR(1),
    protest_info            CHAR(1),
    park_id                 VARCHAR(5),
    attendance              INTEGER,
    time_in_minutes         INTEGER,
    visiting_line_score     TEXT,
    home_line_score         TEXT,
    v_ab                    INTEGER,
    v_h                     INTEGER,
    v_2b                    INTEGER,
    v_3b                    INTEGER,
    v_hr                    INTEGER,
    v_rbi                   INTEGER,
    v_sh                    INTEGER,
    v_sf                    INTEGER,
    v_hbp                   INTEGER,
    v_bb                    INTEGER,
    v_ibb                   INTEGER,
    v_so                    INTEGER,
    v_sb                    INTEGER,
    v_cs                    INTEGER,
    v_gidp                  INTEGER,
    v_ci                    INTEGER,
    v_lob                   INTEGER,
    v_pitchers              INTEGER,
    v_er_indiv              INTEGER,
    v_er_team               INTEGER,
    v_wp                    INTEGER,
    v_balks                 INTEGER,
    v_po                    INTEGER,
    v_a                     INTEGER,
    v_e                     INTEGER,
    v_pb                    INTEGER,
    v_dp                    INTEGER,
    v_tp                    INTEGER,
    h_ab                    INTEGER,
    h_h                     INTEGER,
    h_2b                    INTEGER,
    h_3b                    INTEGER,
    h_hr                    INTEGER,
    h_rbi                   INTEGER,
    h_sh                    INTEGER,
    h_sf                    INTEGER,
    h_hbp                   INTEGER,
    h_bb                    INTEGER,
    h_ibb                   INTEGER,
    h_so                    INTEGER,
    h_sb                    INTEGER,
    h_cs                    INTEGER,
    h_gidp                  INTEGER,
    h_ci                    INTEGER,
    h_lob                   INTEGER,
    h_pitchers              INTEGER,
    h_er_indiv              INTEGER,
    h_er_team               INTEGER,
    h_wp                    INTEGER,
    h_balks                 INTEGER,
    h_po                    INTEGER,
    h_a                     INTEGER,
    h_e                     INTEGER,
    h_pb                    INTEGER,
    h_dp                    INTEGER,
    h_tp                    INTEGER,
    ump_hp_id               VARCHAR(8),
    ump_hp_name             TEXT,
    ump_1b_id               VARCHAR(8),
    ump_1b_name             TEXT,
    ump_2b_id               VARCHAR(8),
    ump_2b_name             TEXT,
    ump_3b_id               VARCHAR(8),
    ump_3b_name             TEXT,
    ump_lf_id               VARCHAR(8),
    ump_lf_name             TEXT,
    ump_rf_id               VARCHAR(8),
    ump_rf_name             TEXT,
    v_manager_id            VARCHAR(8),
    v_manager_name          TEXT,
    h_manager_id            VARCHAR(8),
    h_manager_name          TEXT,
    winning_pitcher_id      VARCHAR(8),
    winning_pitcher_name    TEXT,
    losing_pitcher_id       VARCHAR(8),
    losing_pitcher_name     TEXT,
    saving_pitcher_id       VARCHAR(8),
    saving_pitcher_name     TEXT,
    gwrbi_id                VARCHAR(8),
    gwrbi_name              TEXT,
    v_starting_pitcher_id   VARCHAR(8),
    v_starting_pitcher_name TEXT,
    h_starting_pitcher_id   VARCHAR(8),
    h_starting_pitcher_name TEXT,
    v_player_1_id           VARCHAR(8),
    v_player_1_name         TEXT,
    v_player_1_pos          INTEGER,
    v_player_2_id           VARCHAR(8),
    v_player_2_name         TEXT,
    v_player_2_pos          INTEGER,
    v_player_3_id           VARCHAR(8),
    v_player_3_name         TEXT,
    v_player_3_pos          INTEGER,
    v_player_4_id           VARCHAR(8),
    v_player_4_name         TEXT,
    v_player_4_pos          INTEGER,
    v_player_5_id           VARCHAR(8),
    v_player_5_name         TEXT,
    v_player_5_pos          INTEGER,
    v_player_6_id           VARCHAR(8),
    v_player_6_name         TEXT,
    v_player_6_pos          INTEGER,
    v_player_7_id           VARCHAR(8),
    v_player_7_name         TEXT,
    v_player_7_pos          INTEGER,
    v_player_8_id           VARCHAR(8),
    v_player_8_name         TEXT,
    v_player_8_pos          INTEGER,
    v_player_9_id           VARCHAR(8),
    v_player_9_name         TEXT,
    v_player_9_pos          INTEGER,
    h_player_1_id           VARCHAR(8),
    h_player_1_name         TEXT,
    h_player_1_pos          INTEGER,
    h_player_2_id           VARCHAR(8),
    h_player_2_name         TEXT,
    h_player_2_pos          INTEGER,
    h_player_3_id           VARCHAR(8),
    h_player_3_name         TEXT,
    h_player_3_pos          INTEGER,
    h_player_4_id           VARCHAR(8),
    h_player_4_name         TEXT,
    h_player_4_pos          INTEGER,
    h_player_5_id           VARCHAR(8),
    h_player_5_name         TEXT,
    h_player_5_pos          INTEGER,
    h_player_6_id           VARCHAR(8),
    h_player_6_name         TEXT,
    h_player_6_pos          INTEGER,
    h_player_7_id           VARCHAR(8),
    h_player_7_name         TEXT,
    h_player_7_pos          INTEGER,
    h_player_8_id           VARCHAR(8),
    h_player_8_name         TEXT,
    h_player_8_pos          INTEGER,
    h_player_9_id           VARCHAR(8),
    h_player_9_name         TEXT,
    h_player_9_pos          INTEGER,
    additional_info         TEXT,
    acquisition_info        CHAR(1),
    PRIMARY KEY (home_team, game_date, game_number)
);

COMMENT ON TABLE retrosheet.gamelogs IS 'Complete game log records containing 161 fields of statistical data per game.';
COMMENT ON COLUMN retrosheet.gamelogs.game_date IS 'Date of the game (Format: YYYYMMDD).';
COMMENT ON COLUMN retrosheet.gamelogs.outs_total IS 'Length of the game in outs (e.g., 54 for a standard 9-inning game).';
COMMENT ON COLUMN retrosheet.gamelogs.acquisition_info IS 'Code for how the data was acquired (Y=Official, N=Unofficial, D=Daily Log, P=Partial).';

CREATE TABLE IF NOT EXISTS retrosheet.gameinfo (
    gid         TEXT PRIMARY KEY,
    visteam     TEXT,
    hometeam    TEXT,
    site        TEXT,
    date        DATE,
    number      INTEGER,
    starttime   TEXT,
    daynight    TEXT,
    innings     INTEGER,
    tiebreaker  TEXT,
    usedh       TEXT,
    htbf        TEXT,
    timeofgame  INTEGER,
    attendance  INTEGER,
    fieldcond   TEXT,
    precip      TEXT,
    sky         TEXT,
    temp        INTEGER,
    winddir     TEXT,
    windspeed   INTEGER,
    oscorer     TEXT,
    forfeit     TEXT,
    suspend     TEXT,
    umphome     TEXT,
    ump1b       TEXT,
    ump2b       TEXT,
    ump3b       TEXT,
    umplf       TEXT,
    umprf       TEXT,
    wp          TEXT,
    lp          TEXT,
    save        TEXT,
    gametype    TEXT,
    vruns       INTEGER,
    hruns       INTEGER,
    wteam       TEXT,
    lteam       TEXT,
    line        TEXT,
    batteries   TEXT,
    lineups     TEXT,
    box         TEXT,
    pbp         TEXT,
    season      INTEGER,
    FOREIGN KEY (site) REFERENCES retrosheet.parks(site),
    FOREIGN KEY (visteam) REFERENCES retrosheet.teams(team),
    FOREIGN KEY (hometeam) REFERENCES retrosheet.teams(team)
);

COMMENT ON TABLE retrosheet.gameinfo IS 'Metadata for games, including conditions, umpires, and box/pbp status.';

-- ==========================================
-- 4. Play-by-Play & Statistics
-- ==========================================

CREATE TABLE IF NOT EXISTS retrosheet.plays_raw (
    gid         TEXT NOT NULL,
    event       TEXT NOT NULL,
    inning      INTEGER,
    top_bot     INTEGER,
    vis_home    INTEGER,
    site        TEXT,
    batteam     TEXT,
    pitteam     TEXT,
    score_v     INTEGER,
    score_h     INTEGER,
    batter      TEXT,
    pitcher     TEXT,
    lp          INTEGER,
    bat_f       INTEGER,
    bathand     CHAR(1),
    pithand     CHAR(1),
    balls       INTEGER,
    strikes     INTEGER,
    "count"     TEXT,
    pitches     TEXT,
    nump        INTEGER,
    pa          INTEGER,
    ab          INTEGER,
    single      INTEGER,
    double      INTEGER,
    triple      INTEGER,
    hr          INTEGER,
    sh          INTEGER,
    sf          INTEGER,
    hbp         INTEGER,
    walk        INTEGER,
    k           INTEGER,
    xi          INTEGER,
    roe         INTEGER,
    fc          INTEGER,
    othout      INTEGER,
    noout       INTEGER,
    oth         INTEGER,
    bip         INTEGER,
    bunt        INTEGER,
    ground      INTEGER,
    fly         INTEGER,
    line        INTEGER,
    iw          INTEGER,
    gdp         INTEGER,
    othdp       INTEGER,
    tp          INTEGER,
    fle         INTEGER,
    wp          INTEGER,
    pb          INTEGER,
    bk          INTEGER,
    oa          INTEGER,
    di          INTEGER,
    sb2         INTEGER,
    sb3         INTEGER,
    sbh         INTEGER,
    cs2         INTEGER,
    cs3         INTEGER,
    csh         INTEGER,
    pko1        INTEGER,
    pko2        INTEGER,
    pko3        INTEGER,
    k_safe      INTEGER,
    e1          INTEGER,
    e2          INTEGER,
    e3          INTEGER,
    e4          INTEGER,
    e5          INTEGER,
    e6          INTEGER,
    e7          INTEGER,
    e8          INTEGER,
    e9          INTEGER,
    outs_pre    INTEGER,
    outs_post   INTEGER,
    br1_pre     TEXT,
    br2_pre     TEXT,
    br3_pre     TEXT,
    br1_post    TEXT,
    br2_post    TEXT,
    br3_post    TEXT,
    lob_id1     TEXT,
    lob_id2     TEXT,
    lob_id3     TEXT,
    pr1_pre     TEXT,
    pr2_pre     TEXT,
    pr3_pre     TEXT,
    pr1_post    TEXT,
    pr2_post    TEXT,
    pr3_post    TEXT,
    run_b       TEXT,
    run1        TEXT,
    run2        TEXT,
    run3        TEXT,
    prun_b      TEXT,
    prun1       TEXT,
    prun2       TEXT,
    prun3       TEXT,
    ur_b        INTEGER,
    ur1         INTEGER,
    ur2         INTEGER,
    ur3         INTEGER,
    rbi_b       INTEGER,
    rbi1        INTEGER,
    rbi2        INTEGER,
    rbi3        INTEGER,
    runs        INTEGER,
    rbi         INTEGER,
    er          INTEGER,
    tur         INTEGER,
    l1          TEXT,
    l2          TEXT,
    l3          TEXT,
    l4          TEXT,
    l5          TEXT,
    l6          TEXT,
    l7          TEXT,
    l8          TEXT,
    l9          TEXT,
    lf1         INTEGER,
    lf2         INTEGER,
    lf3         INTEGER,
    lf4         INTEGER,
    lf5         INTEGER,
    lf6         INTEGER,
    lf7         INTEGER,
    lf8         INTEGER,
    lf9         INTEGER,
    f2          TEXT,
    f3          TEXT,
    f4          TEXT,
    f5          TEXT,
    f6          TEXT,
    f7          TEXT,
    f8          TEXT,
    f9          TEXT,
    po0         INTEGER,
    po1         INTEGER,
    po2         INTEGER,
    po3         INTEGER,
    po4         INTEGER,
    po5         INTEGER,
    po6         INTEGER,
    po7         INTEGER,
    po8         INTEGER,
    po9         INTEGER,
    a1          INTEGER,
    a2          INTEGER,
    a3          INTEGER,
    a4          INTEGER,
    a5          INTEGER,
    a6          INTEGER,
    a7          INTEGER,
    a8          INTEGER,
    a9          INTEGER,
    fseq        TEXT,
    batout1     INTEGER,
    batout2     INTEGER,
    batout3     INTEGER,
    brout_b     INTEGER,
    brout1      INTEGER,
    brout2      INTEGER,
    brout3      INTEGER,
    firstf      INTEGER,
    loc         TEXT,
    hittype     TEXT,
    dpopp       INTEGER,
    pivot       INTEGER,
    pn          INTEGER,
    umphome     TEXT,
    ump1b       TEXT,
    ump2b       TEXT,
    ump3b       TEXT,
    umplf       TEXT,
    umprf       TEXT,
    date        DATE,
    gametype    TEXT,
    pbp         TEXT,
    FOREIGN KEY (gid) REFERENCES retrosheet.gameinfo(gid),
    FOREIGN KEY (batter) REFERENCES retrosheet.personnel(id),
    FOREIGN KEY (pitcher) REFERENCES retrosheet.personnel(id)
);

COMMENT ON TABLE retrosheet.plays_raw IS 'Detailed event-by-event play records parsed from Retrosheet event files.';

-- (Batting, Pitching, Fielding tables remain defined but I will add comments)
CREATE TABLE IF NOT EXISTS retrosheet.batting (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    b_lp        INTEGER,
    b_seq       INTEGER,
    stattype    TEXT NOT NULL,
    b_pa        INTEGER,
    b_ab        INTEGER,
    b_r         INTEGER,
    b_h         INTEGER,
    b_d         INTEGER,
    b_t         INTEGER,
    b_hr        INTEGER,
    b_rbi       INTEGER,
    b_sh        INTEGER,
    b_sf        INTEGER,
    b_hbp       INTEGER,
    b_w         INTEGER,
    b_iw        INTEGER,
    b_k         INTEGER,
    b_sb        INTEGER,
    b_cs        INTEGER,
    b_gdp       INTEGER,
    b_xi        INTEGER,
    b_roe       INTEGER,
    dh          INTEGER,
    ph          INTEGER,
    pr          INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, stattype),
    FOREIGN KEY (gid) REFERENCES retrosheet.gameinfo(gid),
    FOREIGN KEY (id) REFERENCES retrosheet.personnel(id)
);

COMMENT ON TABLE retrosheet.batting IS 'In-game batting statistics for each player per game.';

CREATE TABLE IF NOT EXISTS retrosheet.pitching (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    p_seq       INTEGER,
    stattype    TEXT NOT NULL,
    p_ipouts    INTEGER,
    p_noout     INTEGER,
    p_bfp       INTEGER,
    p_h         INTEGER,
    p_d         INTEGER,
    p_t         INTEGER,
    p_hr        INTEGER,
    p_r         INTEGER,
    p_er        INTEGER,
    p_w         INTEGER,
    p_iw        INTEGER,
    p_k         INTEGER,
    p_hbp       INTEGER,
    p_wp        INTEGER,
    p_bk        INTEGER,
    p_sh        INTEGER,
    p_sf        INTEGER,
    p_sb        INTEGER,
    p_cs        INTEGER,
    p_pb        INTEGER,
    wp          INTEGER,
    lp          INTEGER,
    save        INTEGER,
    gs          INTEGER,
    gf          INTEGER,
    cg          INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, stattype),
    FOREIGN KEY (gid) REFERENCES retrosheet.gameinfo(gid),
    FOREIGN KEY (id) REFERENCES retrosheet.personnel(id)
);

COMMENT ON TABLE retrosheet.pitching IS 'In-game pitching statistics for each pitcher per game.';

CREATE TABLE IF NOT EXISTS retrosheet.fielding (
    gid         TEXT NOT NULL,
    id          TEXT NOT NULL,
    team        TEXT NOT NULL,
    d_seq       INTEGER,
    d_pos       INTEGER,
    stattype    TEXT NOT NULL,
    d_ifouts    INTEGER,
    d_po        INTEGER,
    d_a         INTEGER,
    d_e         INTEGER,
    d_dp        INTEGER,
    d_tp        INTEGER,
    d_pb        INTEGER,
    d_wp        INTEGER,
    d_sb        INTEGER,
    d_cs        INTEGER,
    d_gs        INTEGER,
    date        DATE,
    number      INTEGER,
    site        TEXT,
    vishome     CHAR(1),
    opp         TEXT,
    win         INTEGER,
    loss        INTEGER,
    tie         INTEGER,
    gametype    TEXT,
    box         TEXT,
    pbp         TEXT,
    PRIMARY KEY (gid, id, team, d_seq, d_pos, stattype),
    FOREIGN KEY (gid) REFERENCES retrosheet.gameinfo(gid),
    FOREIGN KEY (id) REFERENCES retrosheet.personnel(id)
);

COMMENT ON TABLE retrosheet.fielding IS 'In-game fielding statistics for each player per position per game.';

-- ==========================================
-- 5. Specialized Historical Data
-- ==========================================

CREATE TABLE IF NOT EXISTS retrosheet.rosters (
    player_id       TEXT,
    lastname        TEXT,
    firstname       TEXT,
    bats            CHAR(1),
    throws          CHAR(1),
    team            TEXT,
    pos             TEXT,
    season          INTEGER,
    PRIMARY KEY (player_id, team, season)
);

COMMENT ON TABLE retrosheet.rosters IS 'Seasonal team roster assignments extracted from .ROS files.';

CREATE TABLE IF NOT EXISTS retrosheet.milestones (
    type            TEXT,
    game_id         TEXT,
    date            DATE,
    player_id       TEXT,
    team            TEXT,
    opponent        TEXT,
    details         TEXT
);

COMMENT ON TABLE retrosheet.milestones IS 'Central repository for specialized milestone lists (No-hitters, 3+ HR games, etc.).';

CREATE TABLE IF NOT EXISTS retrosheet.ejections (
    gameid          TEXT,
    date            DATE,
    dh              INTEGER,
    ejectee         TEXT,
    ejecteename     TEXT,
    team            TEXT,
    job             CHAR(1),
    umpire          TEXT,
    umpirename      TEXT,
    inning          INTEGER,
    reason          TEXT,
    FOREIGN KEY (ejectee) REFERENCES retrosheet.personnel(id),
    FOREIGN KEY (umpire) REFERENCES retrosheet.personnel(id)
);

COMMENT ON TABLE retrosheet.ejections IS 'Detailed records of in-game ejections.';

CREATE TABLE IF NOT EXISTS retrosheet.transactions (
    date            DATE,
    seq             INTEGER,
    person_id       TEXT,
    type            CHAR(1),
    from_team       TEXT,
    to_team         TEXT,
    info            TEXT,
    PRIMARY KEY (date, seq, person_id)
);

COMMENT ON TABLE retrosheet.transactions IS 'Player movements database (Trades, Free Agency, Drafts).';

CREATE TABLE IF NOT EXISTS retrosheet.schedules (
    date            DATE,
    number          INTEGER,
    day_of_week     CHAR(3),
    vis_team        TEXT,
    vis_league      CHAR(2),
    vis_game_num    INTEGER,
    home_team       TEXT,
    home_league     CHAR(2),
    home_game_num   INTEGER,
    day_night       CHAR(1),
    postponed       TEXT,
    makeup_date     DATE,
    PRIMARY KEY (date, number, vis_team, home_team)
);

COMMENT ON TABLE retrosheet.schedules IS 'Historical and future game schedules.';

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_gamelogs_date ON retrosheet.gamelogs(game_date);
CREATE INDEX IF NOT EXISTS idx_gamelogs_teams ON retrosheet.gamelogs(visiting_team, home_team);
CREATE INDEX IF NOT EXISTS idx_gameinfo_season ON retrosheet.gameinfo(season);
CREATE INDEX IF NOT EXISTS idx_rosters_team_season ON retrosheet.rosters(team, season);
CREATE INDEX IF NOT EXISTS idx_milestones_type ON retrosheet.milestones(type);
